name: Destroy PR Environment
on:
  pull_request:
    types:  [closed]
  workflow_dispatch:
jobs:
  destroy:
    env:
      NAMESPACE: pr${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Dependencies UI
        run: npm install
        working-directory: ./ui

      - name: Build UI
        run: npm run build
        working-directory: ./ui

      - name: Install Dependencies CDN
        run: npm install
        working-directory: ./example-content-delivery-network

      - name: Destroy CDN
        run: npm run destroy
        working-directory: ./example-content-delivery-network